#pragma once
#include <vector>

#include "msim/trade.hpp"
#include "msim/rules.hpp"
#include "msim/types.hpp"

namespace msim::agents {

struct MarketEvent {
  Ts ts{0};
  msim::MarketPhase phase{msim::MarketPhase::Continuous};
  std::vector<msim::Trade> trades; // trades generated by last exchange operation
};

} // namespace msim::agents
